import { Inter } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { GridBackground } from "@/components/ui/background";
// import Header from "./dashboard/_components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Mockstar.ai",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <GridBackground />
          <div className="absolute inset-0 z-10">
            {/* <Header /> */}
              {children}
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
