import { Inter } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { GridBackground } from "@/components/ui/background";
import { Toaster } from "react-hot-toast";
import ScrollToTop from "@/components/ui/scroll-to-top";
// import Header from "./dashboard/_components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Mockstar.ai",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${inter.className} relative`}>
          <GridBackground />
          <div className="relative z-10">
            {/* <Header /> */}
            <Toaster position="top-right" reverseOrder={false} />
            {children}
          </div>
          <ScrollToTop/>
        </body>
      </html>
    </ClerkProvider>
  );
}
